global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: ftn-cloudflare-api
    metrics_path: /metrics
    static_configs:
      - targets: ["ftn-cloudflare-api:8080"]

rule_files:
  - /etc/prometheus/alerts.yml
